import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import * as core from '../core.js';
const {HEROES,makePlayer,inArc,takeDamage,applyUpgrade,createGame,nextWave}=core;
test('strikes respect weapon reach and facing, including angle wrap',()=>{const p={x:0,y:0,facing:Math.PI-.1};assert.equal(inArc(p,{x:-100,y:-2,radius:20},120),true);assert.equal(inArc(p,{x:100,y:0,radius:20},120),false);assert.equal(inArc(p,{x:-200,y:0,radius:20},120),false);});
test('dodge immunity prevents stacked damage and death clamps at zero',()=>{const p=makePlayer(HEROES[0]);p.invulnerable=.1;assert.equal(takeDamage(p,20),false);assert.equal(p.hp,120);p.invulnerable=0;assert.equal(takeDamage(p,200),true);assert.equal(p.hp,0);assert.equal(takeDamage(p,20),false);});
test('upgrades persist through waves, recovery caps, final encounter has exactly one boss',()=>{const g=createGame(HEROES[0]);applyUpgrade(g.p,'power');applyUpgrade(g.p,'vitality');applyUpgrade(g.p,'flow');g.p.hp=149;g.p.flow=95;nextWave(g);assert.equal(g.p.hp,150);assert.equal(g.p.flow,100);assert.equal(g.p.power,1.25);assert.equal(g.p.cost,30);assert.equal(g.enemies.filter(e=>e.type==='archer').length,2);nextWave(g);assert.equal(g.enemies.filter(e=>e.type==='boss').length,1);assert.equal(g.wave,3);});
// Execute the actual game controller with a small DOM adapter; no game rules are copied into tests.
function controller(){const nodes=new Map();function node(){return {style:{},dataset:{},children:[],textContent:'',hidden:false,classList:{add(){},remove(){},toggle(){}},setAttribute(){},addEventListener(){},focus(){},getContext(){return{}},append(b){this.children.push(b)},set innerHTML(v){this.children=[]},get firstElementChild(){return this.children[0]}};}const document={getElementById(id){if(!nodes.has(id))nodes.set(id,node());return nodes.get(id)},querySelectorAll(){return[]},createElement:node,addEventListener(){}};const sandbox={...core,document,Image:class{},performance:{now:()=>0},matchMedia:()=>({matches:false}),localStorage:{getItem:()=>null,setItem(){}},window:{addEventListener(){}},requestAnimationFrame(){},draw(){},loadArt:async()=>{},console,Math};vm.createContext(sandbox);const src=fs.readFileSync(new URL('../game.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace(/^await loadArt.*$/m,'ready=true;');vm.runInContext(src,sandbox);return {run:s=>vm.runInContext(s,sandbox),nodes};}
test('actual controller: all four techniques consume Flow, damage nearby enemies, and respect cooldown',()=>{for(let i=0;i<4;i++){const c=controller();c.run(`selected=HEROES[${i}];start();g.enemies=[{...g.enemies[0],x:g.p.x+70,y:g.p.y,hp:1000,maxHp:1000}];special()`);assert(c.run('g.enemies[0].hp')<1000,HEROES[i].name);assert(c.run('g.p.specialCD')>0);const hp=c.run('g.enemies[0].hp');c.run('special()');assert.equal(c.run('g.enemies[0].hp'),hp);}});
test('actual controller: normal attacks earn renown, wave upgrade and victory are reachable',()=>{const c=controller();c.run('start();g.enemies=[{...g.enemies[0],x:g.p.x+50,y:g.p.y,hp:1}];attack();update(.016)');assert.equal(c.run('g.mode'),'upgrade');assert(c.run('g.score')>0);c.nodes.get('choices').firstElementChild.onclick();assert.equal(c.run('g.wave'),2);assert.equal(c.run('g.p.power'),1.25);c.run('g.enemies=[];update(.016)');c.nodes.get('choices').firstElementChild.onclick();assert.equal(c.run('g.wave'),3);c.run('g.enemies=[];update(.016)');assert.equal(c.run('g.mode'),'victory');assert.equal(c.run('saved[selected.id].wins'),1);});
test('actual controller: dodge prevents damage, defeat can retry, and pause freezes mode',()=>{const c=controller();c.run('start();dodge();hurt(30)');assert.equal(c.run('g.p.hp'),120);c.run('g.p.invulnerable=0;hurt(150);update(.016)');assert.equal(c.run('g.mode'),'defeat');c.run('start();pause()');assert.equal(c.run('g.mode'),'paused');c.run('resume()');assert.equal(c.run('g.mode'),'playing');assert.equal(c.run('g.p.hp'),120);});
test('boss light-hit resistance preserves its telegraph, techniques can interrupt it',()=>{const c=controller();c.run("start();g.enemies=[{...g.enemies[0],type:'boss',hp:1000,wind:.8,target:{x:640,y:500,r:120}}];hit(g.enemies[0],20)");assert.equal(c.run('g.enemies[0].wind'),.8);c.run('hit(g.enemies[0],60,40,.8)');assert.equal(c.run('g.enemies[0].wind'),0);});
