export const ACTS = [
  {
    id: "jade-gate",
    number: 1,
    name: "The Jade Gate",
    cn: "翠門關",
    available: true,
    arena: "arena",
    bossId: "warden",
    next: "bamboo-crossing",
    unlocks: ["guan-yu"],
    hazards: [],
    // Branching pass map: single-node rows auto-march; multi-node rows offer a choice.
    // Node shape "type:encounterId"; rest/event nodes carry no encounter.
    map: {
      rows: [
        ["duel:vanguard"],
        ["ambush:archer-run", "elite:gate-vanguard"],
        ["event:travelers-gift", "rest:roadside", "duel:crossfire", "shop:merchant"],
        ["boss:warden"],
      ],
    },
    encounters: [
      {
        id: "vanguard",
        title: "Break the vanguard",
        tip: "Strike to build Flow. Green drops restore health.",
        enemies: ["guard", "guard", "guard", "guard", "guard"],
      },
      {
        id: "archer-run",
        title: "Run the archers' gauntlet",
        tip: "Two watchers volley from the walls. Keep moving, then close in.",
        enemies: ["archer", "archer", "guard", "archer"],
      },
      {
        id: "gate-vanguard",
        title: "Break the gate guard",
        tip: "Hardened veterans hold the arch. They hit harder and refuse to fall.",
        enemies: ["guard", "guard", "guard"],
        elite: true,
      },
      {
        id: "crossfire",
        title: "Silence the archers",
        tip: "Archers aim along dashed lines. Keep moving.",
        enemies: [
          "guard",
          "archer",
          "guard",
          "guard",
          "archer",
          "guard",
          "guard",
        ],
      },
      {
        id: "warden",
        title: "Reach the far clearing and defeat the Ashen Warden",
        tip: "Below half health, the Warden chains thrusts. Interrupt with a technique.",
        enemies: ["boss", "archer", "guard", "guard", "archer"],
        bossId: "warden",
      },
    ],
  },
  {
    id: "bamboo-crossing",
    number: 2,
    name: "Whispering Bamboo & the River Crossing",
    cn: "幽篁夜渡",
    available: true,
    arena: "bamboo-roam",
    bossId: "night-heron",
    next: "mount-canglan",
    unlocks: ["wu-song"],
    hazards: ["shallows", "razor-wire"],
    // Water shallows slow every step of this act; the map forks like Act I.
    map: {
      rows: [
        ["duel:bamboo-ambush"],
        ["ambush:river-skiff", "elite:bamboo-elite"],
        ["event:travelers-gift", "rest:roadside", "duel:river-skiff", "shop:merchant"],
        ["boss:night-heron"],
      ],
    },
    encounters: [
      {
        id: "bamboo-ambush",
        title: "Ambush in the bamboo grove",
        tip: "Water shallows impede movement. Watch for sudden lunges through the fog.",
        enemies: ["guard", "guard", "guard", "guard"],
        hazards: ["shallows"],
      },
      {
        id: "bamboo-elite",
        title: "Cut down the mist stalkers",
        tip: "Hardened assassins between the stalks. They hit harder and refuse to fall.",
        enemies: ["guard", "guard", "guard"],
        elite: true,
        hazards: ["shallows"],
      },
      {
        id: "river-skiff",
        title: "Silence the river skiffs",
        tip: "Skiff archers volley from the riverbank. Cross the shallows with care.",
        enemies: [
          "guard",
          "archer",
          "guard",
          "guard",
          "archer",
        ],
        hazards: ["shallows"],
      },
      {
        id: "night-heron",
        title: "Duel with the Night Heron",
        tip: "Concentric sonic shockwaves ripple across the water. Beware razor-wire traps.",
        enemies: ["boss", "archer", "guard"],
        bossId: "night-heron",
        hazards: ["shallows", "razor-wire"],
      },
    ],
  },
  {
    id: "mount-canglan",
    number: 3,
    name: "The Clouds of Mount Canglan",
    cn: "滄嵐絕頂",
    available: true,
    arena: "mount-canglan",
    bossId: "lu-bu-rival",
    next: "meridian-citadel",
    unlocks: ["lu-bu"],
    hazards: ["wind-gust", "falling-pillar"],
    map: {
      rows: [
        ["duel:canglan-approach"],
        ["ambush:bell-terrace", "elite:monk-trial"],
        ["duel:windward-cloister"],
        ["boss:lu-bu-rival"],
      ],
    },
    encounters: [
      { id: "canglan-approach", title: "Climb the cloud road",
        tip: "Watch the gusts; they push warriors and arrows across the terrace.",
        enemies: ["guard", "guard", "archer"], unlocks: ["mu-guiying"],
        unlockStory: "Mu Guiying rallies her rescued scouts and joins the climb." },
      { id: "bell-terrace", title: "Answer the bell guard",
        tip: "Dodge the bell guards and falling masonry.",
        enemies: ["guard", "guard", "archer"], unlocks: ["liang-hongyu"],
        unlockStory: "Liang Hongyu answers the temple bell with her war drum and joins the climb." },
      { id: "monk-trial", title: "The armored monks' trial", elite: true,
        tip: "Their iron staffs test your timing; a curio awaits the victor.",
        enemies: ["guard", "guard", "guard"], unlocks: ["liang-hongyu"],
        unlockStory: "Liang Hongyu answers the temple bell with her war drum and joins the climb." },
      { id: "windward-cloister", title: "Cut the Ashen Oath",
        tip: "Break the warding patrol before facing the Flying General.",
        enemies: ["guard", "archer", "guard"], unlocks: ["nie-yinniang"],
        unlockStory: "Nie Yinniang cuts the oath's hidden threads and joins the final ascent." },
      { id: "lu-bu-rival", title: "Free the Flying General",
        tip: "Read the halberd sweep; guard against the heavy lunge and spend Flow on openings.",
        enemies: ["boss"], bossId: "lu-bu-rival" },
    ],
  },
  {
    id: "meridian-citadel",
    number: 4,
    name: "The Imperial Meridian Citadel",
    cn: "紫禁血月",
    available: false,
    arena: null,
    bossId: "sovereign",
    next: null,
    unlocks: [],
    hazards: ["qi-vortex"],
    encounters: [],
  },
];
export const actById = (id) => ACTS.find((act) => act.id === id);
export const BOSSES = {
  warden: {
    name: "The Ashen Warden",
    sprite: "warden-sprite",
    hp: 570,
    phases: [
      {
        at: 1,
        name: "Polearm sweep",
        wind: 1,
        cooldown: 1.3,
        radius: 120,
        damage: 25,
        bursts: 1,
      },
      {
        at: 0.5,
        name: "Ashen fury",
        wind: 0.65,
        cooldown: 0.85,
        radius: 85,
        damage: 28,
        bursts: 3,
      },
    ],
  },
  "night-heron": {
    name: "The Night Heron",
    cn: "夜鷺娘子",
    title: "The Blind Zither-Assassin",
    hp: 620,
    arena: "pagoda-crossing",
    mechanics: ["sonic-rings", "razor-wire"],
    design: {
      perch: "Stone pagoda water pavilion",
      telegraphs: "Rippling concentric soundwave arcs and glinting razor-wire lines",
      lore: "A blind zither-assassin perched upon a stone pagoda. Uses musical sonic shockwaves and razor-wire traps.",
    },
    phases: [
      {
        at: 1,
        name: "Sonic shockwave",
        description: "Musical sonic shockwaves telegraphed as rippling concentric arcs.",
        wind: 1.1,
        cooldown: 1.4,
        radius: 130,
        damage: 24,
        bursts: 1,
      },
      {
        at: 0.5,
        name: "Razor-wire tempest",
        description: "Enraged zither strumming deploying crisscrossing razor-wire traps.",
        wind: 0.7,
        cooldown: 0.9,
        radius: 95,
        damage: 30,
        bursts: 3,
      },
    ],
  },
  "lu-bu-rival": {
    name: "Lü Bu",
    sprite: "lu-bu-rival-sprite",
    hp: 760,
    mechanics: ["explosive-lunge", "wide-halberd-cleave"],
    phases: [
      { at: 1, name: "Halberd sweep", wind: 1.05, cooldown: 1.3, radius: 150, damage: 27, bursts: 1 },
      { at: 0.5, name: "Ashen Oath lunge", wind: 0.7, cooldown: 0.9, radius: 130, damage: 32, bursts: 2 },
    ],
  },
  sovereign: {
    name: "The Ashen Sovereign",
    planned: true,
    mechanics: ["weapon-forms", "meridian-tempest", "perfect-evade-duel"],
  },
};
export const CULTIVATIONS = [
  {
    id: "iron-vessel",
    name: "Iron vessel",
    description: "+15 maximum health per rank.",
    baseCost: 300,
    maxRank: 3,
    effect: "maxHp",
    amount: 15,
  },
  {
    id: "flow-retention",
    name: "Quiet current",
    description: "+10 starting Flow per rank.",
    baseCost: 250,
    maxRank: 3,
    effect: "flow",
    amount: 10,
  },
  {
    id: "keen-edge",
    name: "Honed edge",
    description: "+5% damage per rank.",
    baseCost: 400,
    maxRank: 3,
    effect: "power",
    amount: 0.05,
  },
];
