export const ACTS = [
  {
    id: "jade-gate",
    number: 1,
    name: "The Jade Gate",
    cn: "翠門關",
    available: true,
    arena: "arena",
    bossId: "warden",
    next: "bamboo-crossing",
    unlocks: [],
    hazards: [],
    // Branching pass map: single-node rows auto-march; multi-node rows offer a choice.
    // Node shape "type:encounterId"; rest/event nodes carry no encounter.
    map: {
      rows: [
        ["duel:vanguard"],
        ["ambush:archer-run", "elite:gate-vanguard"],
        ["event:travelers-gift", "rest:roadside", "duel:crossfire", "shop:merchant"],
        ["boss:warden"],
      ],
    },
    encounters: [
      {
        id: "vanguard",
        title: "Break the vanguard",
        tip: "Strike to build Flow. Green drops restore health.",
        enemies: ["guard", "guard", "guard", "guard", "guard"],
      },
      {
        id: "archer-run",
        title: "Run the archers' gauntlet",
        tip: "Two watchers volley from the walls. Keep moving, then close in.",
        enemies: ["archer", "archer", "guard", "archer"],
      },
      {
        id: "gate-vanguard",
        title: "Break the gate guard",
        tip: "Hardened veterans hold the arch. They hit harder and refuse to fall.",
        enemies: ["guard", "guard", "guard"],
        elite: true,
      },
      {
        id: "crossfire",
        title: "Silence the archers",
        tip: "Archers aim along dashed lines. Keep moving.",
        enemies: [
          "guard",
          "archer",
          "guard",
          "guard",
          "archer",
          "guard",
          "guard",
        ],
      },
      {
        id: "warden",
        title: "Reach the far clearing and defeat the Ashen Warden",
        tip: "Below half health, the Warden chains thrusts. Interrupt with a technique.",
        enemies: ["boss", "archer", "guard", "guard", "archer"],
        bossId: "warden",
      },
    ],
  },
  {
    id: "bamboo-crossing",
    number: 2,
    name: "Whispering Bamboo & the River Crossing",
    cn: "幽篁夜渡",
    available: true,
    arena: "bamboo-roam",
    bossId: "night-heron",
    next: "mount-canglan",
    unlocks: [],
    hazards: ["shallows", "razor-wire"],
    // Water shallows slow every step of this act; the map forks like Act I.
    map: {
      rows: [
        ["duel:bamboo-ambush"],
        ["ambush:river-skiff", "elite:bamboo-elite"],
        ["event:travelers-gift", "rest:roadside", "duel:river-skiff", "shop:merchant"],
        ["boss:night-heron"],
      ],
    },
    encounters: [
      {
        id: "bamboo-ambush",
        title: "Ambush in the bamboo grove",
        tip: "Water shallows impede movement. Watch for sudden lunges through the fog.",
        enemies: ["guard", "guard", "guard", "guard"],
        hazards: ["shallows"],
      },
      {
        id: "bamboo-elite",
        title: "Cut down the mist stalkers",
        tip: "Hardened assassins between the stalks. They hit harder and refuse to fall.",
        enemies: ["guard", "guard", "guard"],
        elite: true,
        hazards: ["shallows"],
      },
      {
        id: "river-skiff",
        title: "Silence the river skiffs",
        tip: "Skiff archers volley from the riverbank. Cross the shallows with care.",
        enemies: [
          "guard",
          "archer",
          "guard",
          "guard",
          "archer",
        ],
        hazards: ["shallows"],
      },
      {
        id: "night-heron",
        title: "Duel with the Night Heron",
        tip: "Concentric sonic shockwaves ripple across the water. Beware razor-wire traps.",
        enemies: ["boss", "archer", "guard"],
        bossId: "night-heron",
        hazards: ["shallows", "razor-wire"],
      },
    ],
  },
  {
    id: "mount-canglan",
    number: 3,
    name: "The Clouds of Mount Canglan",
    cn: "滄嵐絕頂",
    available: true,
    arena: "mount-canglan",
    bossId: "lu-bu-rival",
    next: "meridian-citadel",
    unlocks: [],
    hazards: ["wind-gust", "falling-pillar"],
    map: {
      rows: [
        ["duel:canglan-approach"],
        ["ambush:bell-terrace", "elite:monk-trial"],
        ["duel:windward-cloister"],
        ["boss:lu-bu-rival"],
      ],
    },
    encounters: [
      { id: "canglan-approach", title: "Climb the cloud road",
        tip: "Watch the gusts; they push warriors and arrows across the terrace.",
        enemies: ["guard", "guard", "archer"], unlocks: [], },
      { id: "bell-terrace", title: "Answer the bell guard",
        tip: "Dodge the bell guards and falling masonry.",
        enemies: ["guard", "guard", "archer"], unlocks: [], },
      { id: "monk-trial", title: "The armored monks' trial", elite: true,
        tip: "Their iron staffs test your timing; a curio awaits the victor.",
        enemies: ["guard", "guard", "guard"], unlocks: [], },
      { id: "windward-cloister", title: "Cut the Ashen Oath",
        tip: "Break the warding patrol before facing the Flying General.",
        enemies: ["guard", "archer", "guard"], unlocks: [], },
      { id: "lu-bu-rival", title: "Free the Flying General",
        tip: "Read the halberd sweep; guard against the heavy lunge and spend Flow on openings.",
        enemies: ["boss"], bossId: "lu-bu-rival" },
    ],
  },
  {
    id: "meridian-citadel",
    number: 4,
    name: "The Imperial Meridian Citadel",
    cn: "紫禁血月",
    available: true,
    arena: "meridian-citadel",
    bossId: "sovereign",
    next: "otherworld",
    unlocks: [],
    hazards: ["qi-vortex"],
    map: {
      rows: [
        ["duel:citadel-gate"],
        ["ambush:meridian-wall", "elite:inner-guard"],
        ["event:travelers-gift", "rest:roadside", "duel:citadel-watch", "shop:merchant"],
        ["boss:sovereign"],
      ],
    },
    encounters: [
      { id: "citadel-gate", title: "Enter through the bleeding gate",
        tip: "Sentinels bar the first moon gate. The blood moon watches.",
        enemies: ["guard", "guard", "archer"] },
      { id: "meridian-wall", title: "Run the wall watchers",
        tip: "Acolytes channel the qi vortex from the parapets. Keep moving.",
        enemies: ["archer", "guard", "archer"] },
      { id: "inner-guard", title: "Break the inner guard", elite: true,
        tip: "The Sovereign's own sentinels. They hit harder and drop a curio.",
        enemies: ["guard", "guard", "guard"] },
      { id: "citadel-watch", title: "Cut the citadel watch",
        tip: "The last patrol before the throne. Rest or shop before the moon rises.",
        enemies: ["guard", "archer", "guard"] },
      { id: "sovereign", title: "Face the Ashen Sovereign",
        tip: "Below half health the Blood Moon Edict falls twice as often. Break the gathering with techniques.",
        enemies: ["boss"], bossId: "sovereign" },
    ],
  },
  {
    // Act V: the Sovereign's fall tears a rift that flings the trio a hundred
    // years onward into a pocket otherworld, where twenty stolen legends
    // guard the only bridge home. Scenes: rift, corpse street, hall of
    // twenty, first round, cloud causeway.
    id: "otherworld",
    number: 5,
    name: "The Rift and the Hall of Twenty",
    cn: "裂口 · 廿賢殿",
    available: true,
    arena: "meridian-citadel",
    bossId: "zhao-min-rival",
    next: null,
    unlocks: [],
    hazards: [],
    map: {
      rows: [
        ["duel:rift-street"],
        ["event:travelers-gift", "rest:roadside", "elite:hall-watch"],
        ["duel:hall-of-twenty"],
        ["duel:lattice-first-round", "rest:roadside"],
        ["boss:zhao-min-rival"],
      ],
    },
    encounters: [
      { id: "rift-street", title: "Land on the corpse street",
        tip: "The rift spits you out over a fog-bound street of the unburied. The twenty's inspectors come to appraise the strays.",
        enemies: ["guard", "guard", "archer"] },
      { id: "hall-watch", title: "Break the hall watch", elite: true,
        tip: "Stewards and strategists screen the great gate. They hit harder and drop a curio.",
        enemies: ["guard", "guard", "guard"] },
      { id: "hall-of-twenty", title: "Refuse the hall's judgement", intro: "hall-reveal",
        tip: "Twenty desks in ranked rows. Defy the regent and her bench answers.",
        enemies: ["guard", "archer", "guard"] },
      { id: "lattice-first-round", title: "First round in the lattice halls", intro: "first-round",
        tip: "Screens and silk hide blades. Cut through the pavilion court to reach the causeway stair.",
        enemies: ["guard", "guard", "archer"] },
      { id: "zhao-min-rival", title: "Cross the cloud causeway past Zhao Min",
        tip: "The last keeper duels on the bridge. Below half health her verdicts fall twice as fast.",
        enemies: ["boss"], bossId: "zhao-min-rival" },
    ],
  },
];
export const actById = (id) => ACTS.find((act) => act.id === id);
export const BOSSES = {
  warden: {
    name: "The Ashen Warden",
    sprite: "warden-sprite",
    hp: 570,
    phases: [
      {
        at: 1,
        name: "Polearm sweep",
        wind: 1,
        cooldown: 1.3,
        radius: 120,
        damage: 25,
        bursts: 1,
      },
      {
        at: 0.5,
        name: "Ashen fury",
        wind: 0.65,
        cooldown: 0.85,
        radius: 85,
        damage: 28,
        bursts: 3,
      },
    ],
  },
  "night-heron": {
    name: "The Night Heron",
    cn: "夜鷺娘子",
    title: "The Blind Zither-Assassin",
    hp: 620,
    arena: "pagoda-crossing",
    mechanics: ["sonic-rings", "razor-wire"],
    design: {
      perch: "Stone pagoda water pavilion",
      telegraphs: "Rippling concentric soundwave arcs and glinting razor-wire lines",
      lore: "A blind zither-assassin perched upon a stone pagoda. Uses musical sonic shockwaves and razor-wire traps.",
    },
    phases: [
      {
        at: 1,
        name: "Sonic shockwave",
        description: "Musical sonic shockwaves telegraphed as rippling concentric arcs.",
        wind: 1.1,
        cooldown: 1.4,
        radius: 130,
        damage: 24,
        bursts: 1,
      },
      {
        at: 0.5,
        name: "Razor-wire tempest",
        description: "Enraged zither strumming deploying crisscrossing razor-wire traps.",
        wind: 0.7,
        cooldown: 0.9,
        radius: 95,
        damage: 30,
        bursts: 3,
      },
    ],
  },
  "lu-bu-rival": {
    name: "Lü Bu",
    sprite: "lu-bu-rival-sprite",
    hp: 760,
    mechanics: ["explosive-lunge", "wide-halberd-cleave"],
    phases: [
      { at: 1, name: "Halberd sweep", wind: 1.05, cooldown: 1.3, radius: 150, damage: 27, bursts: 1 },
      { at: 0.5, name: "Ashen Oath lunge", wind: 0.7, cooldown: 0.9, radius: 130, damage: 32, bursts: 2 },
    ],
  },
  sovereign: {
    name: "The Ashen Sovereign",
    cn: "灰帝",
    title: "Throne of the Blood Moon",
    mechanics: ["weapon-forms", "meridian-tempest", "perfect-evade-duel"],
    design: {
      perch: "The meridian throne beneath a blood moon",
      telegraphs: "Weapon-form flourishes and spiraling qi vortexes",
      lore: "The author of the Ashen Oath. Each weapon form is a different duel; the Blood Moon Edict gathers twice as fast below half health.",
    },
    phases: [
      { at: 1, name: "First weapon form", wind: 1, cooldown: 1.2, radius: 130, damage: 26, bursts: 1 },
      { at: 0.5, name: "Blood Moon Edict", wind: 0.6, cooldown: 0.8, radius: 90, damage: 30, bursts: 3 },
    ],
  },
  "zhao-min-rival": {
    name: "Zhao Min",
    cn: "趙敏",
    title: "Keeper of the Cloud Causeway",
    mechanics: ["silver-fan-volleys", "bridge-verdicts"],
    design: {
      perch: "The head of the cloud causeway, above a sea of falling mist",
      telegraphs: "Snapped fan verdicts that cross the whole bridge width",
      lore: "The last of the twenty, guarding the only way home. She duels gladly; below half health her verdicts fall twice as fast.",
    },
    phases: [
      { at: 1, name: "Silken fan volley", wind: 0.85, cooldown: 1.05, radius: 135, damage: 26, bursts: 1 },
      { at: 0.5, name: "Verdict of the Silver Storm", wind: 0.55, cooldown: 0.75, radius: 95, damage: 30, bursts: 3 },
    ],
  },
};
export const CULTIVATIONS = [
  {
    id: "iron-vessel",
    name: "Iron vessel",
    description: "+15 maximum health per rank.",
    baseCost: 300,
    maxRank: 3,
    effect: "maxHp",
    amount: 15,
  },
  {
    id: "flow-retention",
    name: "Quiet current",
    description: "+10 starting Flow per rank.",
    baseCost: 250,
    maxRank: 3,
    effect: "flow",
    amount: 10,
  },
  {
    id: "keen-edge",
    name: "Honed edge",
    description: "+5% damage per rank.",
    baseCost: 400,
    maxRank: 3,
    effect: "power",
    amount: 0.05,
  },
];
