export const ACTS = [
  {
    id: "jade-gate",
    number: 1,
    name: "The Jade Gate",
    cn: "翠門關",
    available: true,
    arena: "arena",
    bossId: "warden",
    next: "bamboo-crossing",
    unlocks: [],
    hazards: [],
    encounters: [
      {
        id: "vanguard",
        title: "Break the vanguard",
        tip: "Strike to build Flow. Green drops restore health.",
        enemies: ["guard", "guard", "guard", "guard", "guard"],
      },
      {
        id: "crossfire",
        title: "Silence the archers",
        tip: "Archers aim along dashed lines. Keep moving.",
        enemies: [
          "guard",
          "archer",
          "guard",
          "guard",
          "archer",
          "guard",
          "guard",
        ],
      },
      {
        id: "warden",
        title: "Defeat the Ashen Warden",
        tip: "Below half health, the Warden chains thrusts. Interrupt with a technique.",
        enemies: ["boss", "archer", "guard", "guard", "archer"],
        bossId: "warden",
      },
    ],
  },
  {
    id: "bamboo-crossing",
    number: 2,
    name: "Whispering Bamboo & the River Crossing",
    cn: "幽篁夜渡",
    available: false,
    arena: null,
    bossId: "night-heron",
    next: "mount-canglan",
    unlocks: [],
    hazards: ["shallows", "razor-wire"],
    encounters: [],
  },
  {
    id: "mount-canglan",
    number: 3,
    name: "The Clouds of Mount Canglan",
    cn: "滄嵐絕頂",
    available: false,
    arena: null,
    bossId: "lu-bu-rival",
    next: "meridian-citadel",
    unlocks: ["lu-bu"],
    hazards: ["wind-gust", "falling-pillar"],
    encounters: [],
  },
  {
    id: "meridian-citadel",
    number: 4,
    name: "The Imperial Meridian Citadel",
    cn: "紫禁血月",
    available: false,
    arena: null,
    bossId: "sovereign",
    next: null,
    unlocks: [],
    hazards: ["qi-vortex"],
    encounters: [],
  },
];
export const actById = (id) => ACTS.find((act) => act.id === id);
export const BOSSES = {
  warden: {
    name: "The Ashen Warden",
    sprite: "warden-sprite",
    hp: 570,
    phases: [
      {
        at: 1,
        name: "Polearm sweep",
        wind: 1,
        cooldown: 1.3,
        radius: 120,
        damage: 25,
        bursts: 1,
      },
      {
        at: 0.5,
        name: "Ashen fury",
        wind: 0.65,
        cooldown: 0.85,
        radius: 85,
        damage: 28,
        bursts: 3,
      },
    ],
  },
  "night-heron": {
    name: "The Night Heron",
    planned: true,
    mechanics: ["sonic-rings", "razor-wire"],
  },
  "lu-bu-rival": {
    name: "Lü Bu",
    planned: true,
    mechanics: ["explosive-lunge", "wide-halberd-cleave"],
  },
  sovereign: {
    name: "The Ashen Sovereign",
    planned: true,
    mechanics: ["weapon-forms", "meridian-tempest", "perfect-evade-duel"],
  },
};
export const CULTIVATIONS = [
  {
    id: "iron-vessel",
    name: "Iron vessel",
    description: "+15 maximum health per rank.",
    baseCost: 300,
    maxRank: 3,
    effect: "maxHp",
    amount: 15,
  },
  {
    id: "flow-retention",
    name: "Quiet current",
    description: "+10 starting Flow per rank.",
    baseCost: 250,
    maxRank: 3,
    effect: "flow",
    amount: 10,
  },
  {
    id: "keen-edge",
    name: "Honed edge",
    description: "+5% damage per rank.",
    baseCost: 400,
    maxRank: 3,
    effect: "power",
    amount: 0.05,
  },
];
