export const HEROES = [
  {
    id: "zhao-yun",
    name: "Zhao Yun",
    cn: "趙雲",
    title: "The White Dragon",
    weapon: "Qinggang Jian",
    style: "Precision · Reach",
    hp: 120,
    speed: 245,
    damage: 27,
    reach: 142,
    rate: 0.39,
    color: "#bfe9df",
    skill: "Dragon Rush",
    description:
      "A sword sworn to the people. Precise thrusts and a piercing rush break the enemy line.",
  },
  {
    id: "lu-zhishen",
    name: "Lu Zhishen",
    cn: "魯智深",
    title: "The Flower Monk",
    weapon: "Iron monk spade",
    style: "Resilience · Control",
    hp: 165,
    speed: 205,
    damage: 32,
    reach: 118,
    rate: 0.55,
    color: "#efd091",
    skill: "Mountain Bell",
    description:
      "Stand firm as the mountain. A sweeping spade and stunning shockwave control the crowd.",
  },
  {
    id: "hu-sanniang",
    name: "Hu Sanniang",
    cn: "扈三娘",
    title: "The Crimson Moon",
    weapon: "Paired sabers",
    style: "Agility · Combos",
    hp: 105,
    speed: 290,
    damage: 19,
    reach: 103,
    rate: 0.25,
    color: "#f3b0a4",
    skill: "Crimson Waltz",
    description:
      "Two blades, no hesitation. Swift strikes and a spinning flourish turn movement into mastery.",
  },
  {
    id: "lu-bu",
    name: "Lü Bu",
    cn: "呂布",
    title: "The Flying General",
    weapon: "Crescent halberd",
    style: "Power · Cleave",
    hp: 140,
    speed: 220,
    damage: 40,
    reach: 157,
    rate: 0.62,
    color: "#d7afe3",
    skill: "Skybreaker",
    description:
      "An unstoppable force. A mighty halberd and devastating cleave shatter the Ashen Banner.",
  },
];

export const HERO_IDS = HEROES.map((hero) => hero.id);
