export const HEROES = [
  {
    id: "zhao-yun",
    name: "Zhao Yun",
    cn: "趙雲",
    title: "The White Dragon",
    weapon: "Qinggang Jian",
    style: "Precision · Protection",
    hp: 120,
    speed: 245,
    damage: 27,
    reach: 142,
    rate: 0.39,
    color: "#bfe9df",
    skill: "Dragon Rush",
    description:
      "A sword sworn to the people. Dragon Rush deals double damage and halves the rival’s reply.",
  },
  {
    id: "lu-zhishen",
    name: "Lu Zhishen",
    cn: "魯智深",
    title: "The Flower Monk",
    weapon: "Iron monk spade",
    style: "Resilience · Stun",
    hp: 165,
    speed: 205,
    damage: 32,
    reach: 118,
    rate: 0.55,
    color: "#efd091",
    skill: "Mountain Bell",
    description:
      "Stand firm as the mountain. Mountain Bell stuns the rival for a turn and restores health.",
  },
  {
    id: "hu-sanniang",
    name: "Hu Sanniang",
    cn: "扈三娘",
    title: "The Crimson Moon",
    weapon: "Paired sabers",
    style: "Technique · Recovery",
    hp: 105,
    speed: 290,
    damage: 19,
    reach: 103,
    rate: 0.25,
    color: "#f3b0a4",
    skill: "Crimson Waltz",
    description:
      "Two blades, no hesitation. Crimson Waltz delivers a powerful double-blade strike and restores health.",
  },
  {
    id: "lu-bu",
    name: "Lü Bu",
    cn: "呂布",
    title: "The Flying General",
    weapon: "Crescent halberd",
    style: "Power · Guardbreaker",
    hp: 140,
    speed: 220,
    damage: 40,
    reach: 157,
    rate: 0.62,
    color: "#d7afe3",
    skill: "Skybreaker",
    description:
      "An unstoppable force. Skybreaker delivers devastating damage through the rival’s guard.",
  },
  {
    // Stitch try-run 2026-09-25. Concept sheet art; no dedicated sprite yet,
    // so the pass renders this hero as a framed standee token.
    id: "guan-yu",
    name: "Guan Yu",
    cn: "關羽",
    title: "The Green Dragon",
    weapon: "Crescent blade",
    style: "Might · Honor",
    hp: 150,
    speed: 215,
    damage: 34,
    reach: 150,
    rate: 0.5,
    color: "#a8d5b0",
    skill: "Spring-Autumn Cleave",
    artFocus: "26% 32%",
    description:
      "A lord among warriors. Spring-Autumn Cleave sweeps for heavy damage and braces the line behind the blade.",
  },
  {
    id: "wu-song",
    name: "Wu Song",
    cn: "武松",
    title: "The Tiger Slayer",
    weapon: "Tiger-hunting staff",
    style: "Ferocity · Stun",
    hp: 135,
    speed: 255,
    damage: 29,
    reach: 112,
    rate: 0.34,
    color: "#e8b060",
    skill: "Tiger-Crushing Blow",
    artFocus: "24% 34%",
    description:
      "The tiger of Jingyang Ridge. Tiger-Crushing Break lands a brutal strike that leaves the rival reeling.",
  },
  {
    id: "mu-guiying",
    name: "Mu Guiying",
    cn: "穆桂英",
    title: "The Peerless General",
    weapon: "Pear-blossom spear",
    style: "Command · Versatility",
    hp: 115,
    speed: 270,
    damage: 24,
    reach: 132,
    rate: 0.3,
    color: "#e9a9c0",
    skill: "Pear Blossom Storm",
    artFocus: "30% 30%",
    description:
      "The general who took the gate. Pear Blossom Storm strikes in a drifting flurry, then recovers guard and health.",
  },
  {
    id: "liang-hongyu",
    name: "Liang Hongyu",
    cn: "梁紅玉",
    title: "The Drum-War Widow",
    weapon: "Paired dao",
    style: "Rhythm · Rally",
    hp: 125,
    speed: 250,
    damage: 26,
    reach: 120,
    rate: 0.36,
    color: "#9fb9e8",
    skill: "War Drum Barrage",
    artFocus: "28% 32%",
    description:
      "Drums on the river walls. War Drum Barrage beats a relentless double-blade rhythm and restores fighting spirit.",
  },
  {
    id: "nie-yinniang",
    name: "Nie Yinniang",
    cn: "聶隱娘",
    title: "The Hidden Blade",
    weapon: "Twin short swords",
    style: "Stealth · Evasion",
    hp: 95,
    speed: 305,
    damage: 23,
    reach: 98,
    rate: 0.22,
    color: "#b9aee6",
    skill: "Shadow Step",
    artFocus: "30% 34%",
    description:
      "The assassin who vanished mid-strike. Shadow Step cuts deep, then slips beyond the rival’s reply.",
  },
];

export const HERO_IDS = HEROES.map((hero) => hero.id);
