import {clamp} from './core.js';
export const images={};
export async function loadArt(ids){await Promise.all(ids.map(id=>new Promise(resolve=>{const im=new Image();im.onload=()=>{images[id]=im;resolve()};im.onerror=()=>resolve();im.src=`assets/${id}.png`;})));}
function ellipse(c,x,y,rx,ry,color){c.fillStyle=color;c.beginPath();c.ellipse(x,y,rx,ry,0,0,Math.PI*2);c.fill();}
function ring(c,x,y,r,color,width=2){c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.ellipse(x,y,r,r*.62,0,0,Math.PI*2);c.stroke();}
function actor(c,a,id,size,player,g,reduced){const img=images[id];const bob=player&&a.moving&&!reduced?Math.sin(g.time*17)*2:0;const facing=Math.cos(a.facing)>=0?1:-1;ellipse(c,a.x,a.y+1,size*.19,size*.06,'#0b151a65');if(player){ring(c,a.x,a.y,size*.20,a.invulnerable>0?'#f8e8b8':a.color,2);c.fillStyle='#fff4cb';c.beginPath();c.moveTo(a.x,a.y-size-10);c.lineTo(a.x-5,a.y-size-18);c.lineTo(a.x+5,a.y-size-18);c.fill();}c.save();c.translate(a.x,a.y+bob);c.scale(facing,1);if(a.invulnerable>0)c.globalAlpha=.70+Math.sin(g.time*35)*.2;if(a.flash>0)c.filter='brightness(1.8)';if(player&&a.attackAnim>0){c.rotate(Math.sin(a.attackAnim*12)*.08);c.translate(8,0);}if(img)c.drawImage(img,-size*.55,-size*1.04,size*1.1,size*1.1);else{ellipse(c,0,-35,16,34,player?a.color:'#724940');ellipse(c,0,-75,12,13,'#c9b090');}c.restore();if(!player){c.fillStyle='#142025';c.fillRect(a.x-22,a.y-size*.83,44,4);c.fillStyle=a.type==='boss'?'#d6b376':'#b46c5f';c.fillRect(a.x-22,a.y-size*.83,44*clamp(a.hp/a.maxHp,0,1),4);if(a.stun>0){c.fillStyle='#f5df99';c.font='17px serif';c.textAlign='center';c.fillText('✦',a.x,a.y-size*.9);}}}
export function draw(c,g,reduced=false){const W=1280,H=720;c.clearRect(0,0,W,H);c.save();if(g.shake>0&&!reduced)c.translate((Math.random()-.5)*g.shake,(Math.random()-.5)*g.shake);if(images.arena)c.drawImage(images.arena,0,0,W,H);else{c.fillStyle='#35433e';c.fillRect(0,0,W,H);}c.fillStyle='#14201d20';c.fillRect(0,0,W,H);if(!g.p){c.restore();return;}
for(const e of g.enemies){if(e.wind>0&&e.target){const progress=1-e.wind/e.windMax;const t=e.target;c.save();c.strokeStyle='#ffce9b';c.lineWidth=2;c.setLineDash([7,5]);if(e.type==='archer'){c.beginPath();c.moveTo(e.x,e.y-35);c.lineTo(t.x,t.y-25);c.stroke();}else{ellipse(c,t.x,t.y,t.r,t.r*.65,`rgba(192,52,37,${.14+progress*.28})`);ring(c,t.x,t.y,t.r,'#e76e50',2);ring(c,t.x,t.y,t.r*progress,'#ffd1a5',3);}c.restore();}}
for(const p of g.pickups){ellipse(c,p.x,p.y+2,12,5,'#18272477');ellipse(c,p.x,p.y-8,7,9,'#b3e5a0');ring(c,p.x,p.y,14,'#daf5b9');}
for(const fx of g.effects.filter(x=>x.kind==='ring')){c.globalAlpha=clamp(fx.life/fx.max,0,1);ring(c,fx.x,fx.y,fx.r*(1-fx.life/fx.max)+20,fx.color,6);c.globalAlpha=1;}
const actors=[...g.enemies.map(a=>({a,player:false})),{a:g.p,player:true}].sort((a,b)=>a.a.y-b.a.y);
for(const {a,player} of actors)actor(c,a,player?`${a.id}-sprite`:a.type==='boss'?'warden-sprite':a.type==='archer'?'archer-sprite':'guard-sprite',player?130:a.type==='boss'?165:111,player,g,reduced);
for(const s of g.shots){c.strokeStyle='#ffcc9f';c.lineWidth=3;c.beginPath();c.moveTo(s.x,s.y-28);c.lineTo(s.x-s.vx*.06,s.y-28-s.vy*.06);c.stroke();}
for(const fx of g.effects){const alpha=clamp(fx.life/fx.max,0,1);c.save();c.globalAlpha=alpha;if(fx.kind==='text'){c.font=`bold ${fx.big?24:17}px Georgia`;c.textAlign='center';c.strokeStyle='#122122';c.lineWidth=3;c.strokeText(fx.text,fx.x,fx.y-(1-alpha)*40);c.fillStyle=fx.color;c.fillText(fx.text,fx.x,fx.y-(1-alpha)*40);}if(fx.kind==='slash'){c.translate(fx.x,fx.y-30);c.scale(1,.65);c.rotate(fx.angle);c.strokeStyle=fx.color;c.lineWidth=12*alpha;c.beginPath();c.arc(0,0,fx.r,-1.1,1.1);c.stroke();c.lineWidth=2;c.strokeStyle='#fff6d7';c.stroke();}if(fx.kind==='spark'){c.fillStyle=fx.color;c.fillRect(fx.x+fx.vx*(1-alpha),fx.y+fx.vy*(1-alpha),4,4);}c.restore();}
if(!reduced)for(let i=0;i<16;i++){const x=(i*101+g.time*(11+i%4))%W,y=(i*79+g.time*19)%H;c.save();c.translate(x,y);c.rotate(g.time+i);c.fillStyle='#e4ca8566';c.fillRect(0,0,5,2);c.restore();}c.restore();}
