const HEROES = [
  {name:'Zhao Yun',mark:'趙',title:'THE SILVER EDGE',style:'Precision · balanced',color:'#d5dce2',accent:'#b9362e',image:'../characters/zhao-yun/stitch-v2/concept.jpg',speed:265,damage:24,reach:72,signature:'AZURE LINE'},
  {name:'Lu Zhishen',mark:'魯',title:'THE TEMPLE STORM',style:'Power · control',color:'#bd934c',accent:'#d9b86c',image:'../characters/lu-zhishen/stitch-v2/concept.jpg',speed:220,damage:34,reach:88,signature:'TEMPLE BELL'},
  {name:'Hu Sanniang',mark:'扈',title:'THE CRIMSON MOON',style:'Speed · risk',color:'#bc4640',accent:'#63a17c',image:'../characters/hu-sanniang/stitch-v2/concept.jpg',speed:300,damage:19,reach:66,signature:'MOON SNARE'},
  {name:'Lü Bu',mark:'呂',title:'THE SKY-SPLITTER',style:'Reach · force',color:'#732723',accent:'#d0a85d',image:'../characters/lu-bu/grok-v4/concept.jpg',speed:205,damage:38,reach:104,signature:'SKY SPLITTER'}
];
const $=s=>document.querySelector(s), roster=$('#roster'), selection=$('#selection'), gameEl=$('#game'), canvas=$('#arena'), ctx=canvas.getContext('2d');
let selected=0, running=false, last=0, frame=0, score=0, wave=1, kills=0, keys={}, enemies=[], sparks=[], audioOn=true;
let player={x:300,y:310,hp:100,flow:0,attack:0,dodge:0,inv:0,angle:0};
HEROES.forEach((h,i)=>{const card=document.createElement('article');card.className='card'+(i===0?' selected':'');card.innerHTML=`<img src="${h.image}" alt="${h.name} concept sheet"><div class="copy"><small>${h.mark} · ${h.title}</small><h3>${h.name}</h3><p>${h.style}</p></div>`;card.onclick=()=>select(i);roster.append(card)});
function select(i){selected=(i+HEROES.length)%HEROES.length;[...roster.children].forEach((c,n)=>c.classList.toggle('selected',n===selected));roster.children[selected].scrollIntoView({block:'nearest',inline:'nearest'})}
function start(){selection.hidden=true;gameEl.hidden=false;const h=HEROES[selected];$('#hero-mark').textContent=h.mark;$('#hero-name').textContent=h.name;$('#hero-style').textContent=h.title;reset();setTimeout(()=>$('#message').classList.add('hide'),1100)}
function reset(){cancelAnimationFrame(frame);running=true;last=performance.now();score=0;wave=1;kills=0;enemies=[];sparks=[];player={x:300,y:310,hp:100,flow:0,attack:0,dodge:0,inv:0,angle:0};spawnWave();updateHud();document.querySelector('.game-over')?.remove();frame=requestAnimationFrame(loop)}
function spawnWave(){const count=Math.min(2+wave,7);for(let i=0;i<count;i++)enemies.push({x:820+Math.random()*300,y:90+Math.random()*440,hp:wave===3&&i===0?100:48,r:wave===3&&i===0?25:18,attack:Math.random(),flash:0,elite:wave===3&&i===0});$('#objective').textContent=wave===3?'Break the Iron Guard':'Defeat the ambush';updateHud()}
function attack(signature=false){if(!running)return;const h=HEROES[selected];if(signature&&player.flow<100)return;if(signature)player.flow=0;player.attack=signature?.55:.23;beep(signature?100:240,.06);const radius=signature?190:h.reach;enemies.forEach(e=>{const d=Math.hypot(e.x-player.x,e.y-player.y);if(d<radius){e.hp-=signature?70:h.damage;e.flash=.12;const push=(signature?65:20)/Math.max(d,1);e.x+=(e.x-player.x)*push;e.y+=(e.y-player.y)*push;if(!signature)player.flow=Math.min(100,player.flow+18);for(let n=0;n<5;n++)sparks.push({x:e.x,y:e.y,vx:(Math.random()-.5)*220,vy:(Math.random()-.5)*220,t:.3})}})}
function loop(t){if(!running)return;const dt=Math.min((t-last)/1000,.033);last=t;update(dt);draw();frame=requestAnimationFrame(loop)}
function update(dt){const h=HEROES[selected],dx=(keys.d?1:0)-(keys.a?1:0),dy=(keys.s?1:0)-(keys.w?1:0),len=Math.hypot(dx,dy)||1;if(dx||dy)player.angle=Math.atan2(dy,dx);const mult=player.dodge>0?2.3:1;player.x=Math.max(35,Math.min(canvas.width-35,player.x+dx/len*h.speed*mult*dt));player.y=Math.max(45,Math.min(canvas.height-35,player.y+dy/len*h.speed*mult*dt));player.attack=Math.max(0,player.attack-dt);player.dodge=Math.max(0,player.dodge-dt);player.inv=Math.max(0,player.inv-dt);enemies.forEach(e=>{e.flash=Math.max(0,e.flash-dt);const ex=player.x-e.x,ey=player.y-e.y,d=Math.hypot(ex,ey);e.attack-=dt;if(d>46){e.x+=ex/d*(e.elite?72:92)*dt;e.y+=ey/d*(e.elite?72:92)*dt}else if(e.attack<=0){e.attack=e.elite?1.05:1.45;if(player.inv<=0){player.hp-=e.elite?20:12;player.inv=.65;beep(65,.12)}}});const dead=enemies.filter(e=>e.hp<=0);kills+=dead.length;score+=dead.length*100;enemies=enemies.filter(e=>e.hp>0);sparks.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.t-=dt});sparks=sparks.filter(s=>s.t>0);if(!enemies.length){if(wave<3){wave++;spawnWave()}else finish(true)}if(player.hp<=0)finish(false);updateHud()}
function updateHud(){$('#hp-bar').style.width=Math.max(0,player.hp)+'%';$('#flow-bar').style.width=player.flow+'%';$('#hp-text').textContent=Math.max(0,player.hp);$('#flow-text').textContent=Math.round(player.flow)+'%';$('#enemy-count').textContent=`Enemies · ${enemies.length}  /  Wave ${wave}`}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);const g=ctx.createLinearGradient(0,0,canvas.width,canvas.height);g.addColorStop(0,'#27231c');g.addColorStop(1,'#11100e');ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#b89c6030';ctx.lineWidth=1;for(let i=-200;i<1400;i+=90){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i-300,620);ctx.stroke()}ctx.fillStyle='#0a0908aa';ctx.beginPath();ctx.moveTo(0,90);ctx.lineTo(180,40);ctx.lineTo(340,105);ctx.lineTo(540,55);ctx.lineTo(750,100);ctx.lineTo(920,32);ctx.lineTo(1200,100);ctx.lineTo(1200,0);ctx.lineTo(0,0);ctx.fill();enemies.forEach(drawEnemy);sparks.forEach(s=>{ctx.fillStyle='#e5bd65';ctx.fillRect(s.x,s.y,3,3)});drawPlayer()}
function drawPlayer(){const h=HEROES[selected];ctx.save();ctx.translate(player.x,player.y);if(player.inv>0&&Math.floor(player.inv*12)%2)ctx.globalAlpha=.35;ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(0,16,26,9,0,0,7);ctx.fill();ctx.rotate(player.angle);if(player.attack>0){ctx.strokeStyle=h.accent;ctx.lineWidth=8;ctx.beginPath();ctx.arc(0,0,h.reach,-1.15,1.15);ctx.stroke()}ctx.strokeStyle=h.color;ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(5,0);ctx.lineTo(h.reach*.7,0);ctx.stroke();ctx.fillStyle=h.color;ctx.beginPath();ctx.arc(0,0,20,0,7);ctx.fill();ctx.fillStyle=h.accent;ctx.beginPath();ctx.arc(4,0,8,0,7);ctx.fill();ctx.restore()}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(0,15,e.r+7,8,0,0,7);ctx.fill();ctx.fillStyle=e.flash?'#f0d19a':e.attack<.3?'#b73229':'#4a3932';ctx.beginPath();ctx.arc(0,0,e.r,0,7);ctx.fill();ctx.strokeStyle=e.elite?'#d0a85d':'#958477';ctx.lineWidth=e.elite?5:3;ctx.beginPath();ctx.moveTo(-e.r,0);ctx.lineTo(e.r+18,0);ctx.stroke();ctx.restore()}
function finish(win){running=false;const over=document.createElement('div');over.className='game-over';over.innerHTML=`<small>${win?'PASS CLEARED':'LEGEND INTERRUPTED'}</small><h2>${win?'Victory':'Defeated'}</h2><p>${kills} foes · ${score} renown</p><button type="button">${win?'FIGHT AGAIN':'RISE AGAIN'}</button>`;$('.arena-wrap').append(over);over.querySelector('button').onclick=reset}
function beep(freq,duration){if(!audioOn)return;const ac=beep.ac||(beep.ac=new AudioContext),o=ac.createOscillator(),gain=ac.createGain();o.frequency.value=freq;gain.gain.setValueAtTime(.035,ac.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ac.currentTime+duration);o.connect(gain).connect(ac.destination);o.start();o.stop(ac.currentTime+duration)}
document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(selection.hidden===false&&(k==='arrowright'||k==='arrowleft'))select(selected+(k==='arrowright'?1:-1));if(selection.hidden===false&&e.key==='Enter')start();keys[k]=true;if(k==='j'&&!e.repeat)attack();if(k==='k'&&!e.repeat&&player.dodge<=0){player.dodge=.18;player.inv=.3}if(k==='l'&&!e.repeat)attack(true)});document.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.onpointerdown=e=>{e.preventDefault();keys[k]=true;if(k==='j')attack();if(k==='k'&&player.dodge<=0){player.dodge=.18;player.inv=.3}if(k==='l')attack(true)};b.onpointerup=()=>keys[k]=false;b.onpointerleave=()=>keys[k]=false});$('#begin').onclick=start;$('#restart').onclick=reset;$('#sound').onclick=()=>{$('#sound').textContent=`SOUND · ${(audioOn=!audioOn)?'ON':'OFF'}`};
